apiVersion: apps/v1
kind: Deployment
metadata:
  name: weight-deployment
  labels:
    app: weight
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weight
  template:
    metadata:
      labels:
        app: weight
    spec:
      containers:
      - image: docker.io/nirh237/weight-tracker:69
        name: weight-container
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: weight-config
          - secretRef:
                name: okta-cred
          - configMapRef:
              name: db-config
          - secretRef:
                name: db-cred